//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ChuyenBay
    {
        public int MaChuyenBay { get; set; }
        public Nullable<System.DateTime> NgayCatCanh { get; set; }
        public string DiaDiemDi { get; set; }
        public string DiaDiemDen { get; set; }
        public Nullable<System.DateTime> ThoiGianBay { get; set; }
        public Nullable<System.DateTime> ThoiGianHaCanh { get; set; }
        public Nullable<int> SoGheHangNhat { get; set; }
        public Nullable<int> SoGheHangThuongGia { get; set; }
        public Nullable<int> SoGheHangPhoThongDB { get; set; }
        public Nullable<int> SoGheHangPhoThong { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<decimal> GiaVePhoThong { get; set; }
        public Nullable<int> MaMayBay { get; set; }
        public Nullable<int> MaTuyenBay { get; set; }
    
        public virtual tb_MayBay tb_MayBay { get; set; }
        public virtual tb_TuyenBay tb_TuyenBay { get; set; }
        public virtual tb_DoiBay tb_DoiBay { get; set; }
    }
}
