//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Ghe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Ghe()
        {
            this.tb_DatVe = new HashSet<tb_DatVe>();
        }
    
        public int MaGhe { get; set; }
        public Nullable<int> SoGhe { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string DayGhe { get; set; }
        public Nullable<int> MaHangGhe { get; set; }
        public Nullable<int> MaMayBay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DatVe> tb_DatVe { get; set; }
        public virtual tb_HangGhe tb_HangGhe { get; set; }
        public virtual tb_MayBay tb_MayBay { get; set; }
    }
}
