//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HoaDon
    {
        public int MaHoaDon { get; set; }
        public Nullable<int> ThanhTien { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
    
        public virtual tb_KhachHang tb_KhachHang { get; set; }
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
