//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HangGhe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_HangGhe()
        {
            this.tb_Ghe = new HashSet<tb_Ghe>();
        }
    
        public int MaHangGhe { get; set; }
        public string TenHangGhe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Ghe> tb_Ghe { get; set; }
    }
}
