//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MayBay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_MayBay()
        {
            this.tb_ChuyenBay = new HashSet<tb_ChuyenBay>();
            this.tb_Ghe = new HashSet<tb_Ghe>();
        }
    
        public int MaMayBay { get; set; }
        public string LoaiMayBay { get; set; }
        public string SoHieu { get; set; }
        public Nullable<int> SoGheHangNhat { get; set; }
        public Nullable<int> SoGheHangThuongGia { get; set; }
        public Nullable<int> SoGheHangPTDB { get; set; }
        public Nullable<int> SoGheHangPT { get; set; }
        public string HangSX { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgaySuDung { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChuyenBay> tb_ChuyenBay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Ghe> tb_Ghe { get; set; }
    }
}
