//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_NhanVien()
        {
            this.tb_HoaDon = new HashSet<tb_HoaDon>();
        }
    
        public int MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public string GioiTinh { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public string Matkhau { get; set; }
        public Nullable<int> MaNghiepVu { get; set; }
        public Nullable<int> MaDoiBay { get; set; }
    
        public virtual tb_DoiBay tb_DoiBay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_HoaDon> tb_HoaDon { get; set; }
        public virtual tb_Nghiepvu tb_Nghiepvu { get; set; }
    }
}
