//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TuyenBay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_TuyenBay()
        {
            this.tb_ChuyenBay = new HashSet<tb_ChuyenBay>();
        }
    
        public int MaTuyenBay { get; set; }
        public Nullable<int> MaSanBayDi { get; set; }
        public Nullable<int> MaSanBayDen { get; set; }
    
        public virtual tb_SanBay tb_SanBay { get; set; }
        public virtual tb_SanBay tb_SanBay1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChuyenBay> tb_ChuyenBay { get; set; }
    }
}
